objs = ../neuron.o ../matrix.o
progs  = nums_test save_test faces_test myface_test

CFLAGS = -I../
LDLIBS = -lm
CC = gcc

all:	$(progs)

clean:
	rm $(objs)  $(progs)

nums_test: $(objs)
save_test: $(objs)
faces_test: $(objs)
myface_test: $(objs)
